version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./src:/var/www/html/wp-content/themes/wordpress-boilerplate
      - ./uploads:/var/www/html/wp-content/uploads
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./plugins.csv:/var/www/html/plugins.csv
      - ./plugins.sh:/var/www/html/plugins.sh
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - "8080:80"
    restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "8081:80"
    depends_on:
      - db
